#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Olycksassistenten.Resource", IsApplication=true)]

namespace Olycksassistenten
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Olycksassistenten.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Olycksassistenten.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Olycksassistenten.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Broken2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Krock2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int my_border = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int My_border2 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040056
			public const int buttonAddPhotoOk = 2130968662;
			
			// aapt resource value: 0x7f04000e
			public const int buttonDataDriver1Ok = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int buttonDataDriver1Scan = 2130968589;
			
			// aapt resource value: 0x7f040011
			public const int buttonDescAccidentOk = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int buttonForgSend = 2130968595;
			
			// aapt resource value: 0x7f040043
			public const int buttonPickInsCompanyOk = 2130968643;
			
			// aapt resource value: 0x7f04002f
			public const int buttonRegCreate = 2130968623;
			
			// aapt resource value: 0x7f040040
			public const int buttonRegNoOk = 2130968640;
			
			// aapt resource value: 0x7f040017
			public const int buttonStartLogin = 2130968599;
			
			// aapt resource value: 0x7f040053
			public const int buttonSummarySend = 2130968659;
			
			// aapt resource value: 0x7f040055
			public const int buttonTakePhoto = 2130968661;
			
			// aapt resource value: 0x7f040057
			public const int contentFrame = 2130968663;
			
			// aapt resource value: 0x7f040012
			public const int editForgMail = 2130968594;
			
			// aapt resource value: 0x7f040032
			public const int editRegModel1 = 2130968626;
			
			// aapt resource value: 0x7f04003a
			public const int editRegModel2 = 2130968634;
			
			// aapt resource value: 0x7f040030
			public const int editRegNo1 = 2130968624;
			
			// aapt resource value: 0x7f040038
			public const int editRegNo2 = 2130968632;
			
			// aapt resource value: 0x7f040033
			public const int editRegYear1 = 2130968627;
			
			// aapt resource value: 0x7f04003d
			public const int editRegYear2 = 2130968637;
			
			// aapt resource value: 0x7f040015
			public const int editStartPassword = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int editStartUserName = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int editTextDataMail1 = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int editTextDataPhoneNo1 = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int editTextDescAccident = 2130968591;
			
			// aapt resource value: 0x7f040029
			public const int editTextRegAddress = 2130968617;
			
			// aapt resource value: 0x7f04002e
			public const int editTextRegMail = 2130968622;
			
			// aapt resource value: 0x7f040023
			public const int editTextRegName = 2130968611;
			
			// aapt resource value: 0x7f040020
			public const int editTextRegPassword = 2130968608;
			
			// aapt resource value: 0x7f04002c
			public const int editTextRegPhone = 2130968620;
			
			// aapt resource value: 0x7f040026
			public const int editTextRegSSN = 2130968614;
			
			// aapt resource value: 0x7f04001d
			public const int editTextRegUserName = 2130968605;
			
			// aapt resource value: 0x7f040054
			public const int imageViewTakePhotoWindow = 2130968660;
			
			// aapt resource value: 0x7f04001c
			public const int linearLayout1 = 2130968604;
			
			// aapt resource value: 0x7f04003f
			public const int linearLayout10 = 2130968639;
			
			// aapt resource value: 0x7f040031
			public const int linearLayout11 = 2130968625;
			
			// aapt resource value: 0x7f040039
			public const int linearLayout13 = 2130968633;
			
			// aapt resource value: 0x7f04003c
			public const int linearLayout14 = 2130968636;
			
			// aapt resource value: 0x7f04001f
			public const int linearLayout2 = 2130968607;
			
			// aapt resource value: 0x7f040022
			public const int linearLayout3 = 2130968610;
			
			// aapt resource value: 0x7f040025
			public const int linearLayout4 = 2130968613;
			
			// aapt resource value: 0x7f040028
			public const int linearLayout5 = 2130968616;
			
			// aapt resource value: 0x7f04002b
			public const int linearLayout6 = 2130968619;
			
			// aapt resource value: 0x7f040036
			public const int linearLayout7 = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int linearLayout8 = 2130968631;
			
			// aapt resource value: 0x7f040034
			public const int linearLayout9 = 2130968628;
			
			// aapt resource value: 0x7f04000b
			public const int linearLayoutDataMail = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int linearLayoutDataPhoneNo = 2130968583;
			
			// aapt resource value: 0x7f040041
			public const int spinnerChooseInsuranceCompany1 = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int spinnerChooseInsuranceCompany2 = 2130968642;
			
			// aapt resource value: 0x7f04001a
			public const int textView1 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int textView2 = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int textView3 = 2130968606;
			
			// aapt resource value: 0x7f040021
			public const int textView4 = 2130968609;
			
			// aapt resource value: 0x7f040024
			public const int textView5 = 2130968612;
			
			// aapt resource value: 0x7f040027
			public const int textView6 = 2130968615;
			
			// aapt resource value: 0x7f04002a
			public const int textView7 = 2130968618;
			
			// aapt resource value: 0x7f04002d
			public const int textView8 = 2130968621;
			
			// aapt resource value: 0x7f04003b
			public const int textView9 = 2130968635;
			
			// aapt resource value: 0x7f040005
			public const int textViewDataAddressNo1 = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int textViewDataInsuranceCo1 = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int textViewDataMail1 = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int textViewDataName1 = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int textViewDataPhoneNo1 = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int textViewDataRegNo1 = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int textViewDataSSN1 = 2130968578;
			
			// aapt resource value: 0x7f040035
			public const int textViewFelAngeReg = 2130968629;
			
			// aapt resource value: 0x7f04003e
			public const int textViewFelAngeReg2 = 2130968638;
			
			// aapt resource value: 0x7f040010
			public const int textViewFelFyllIBesk = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int textViewMail1 = 2130968585;
			
			// aapt resource value: 0x7f040019
			public const int textViewStartForgotPassword = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int textViewStartRegAccount = 2130968600;
			
			// aapt resource value: 0x7f040048
			public const int textViewSummaryAddress1 = 2130968648;
			
			// aapt resource value: 0x7f04004f
			public const int textViewSummaryAddress2 = 2130968655;
			
			// aapt resource value: 0x7f040052
			public const int textViewSummaryDesc = 2130968658;
			
			// aapt resource value: 0x7f040047
			public const int textViewSummaryInsuranceCo1 = 2130968647;
			
			// aapt resource value: 0x7f04004e
			public const int textViewSummaryInsuranceCo2 = 2130968654;
			
			// aapt resource value: 0x7f04004a
			public const int textViewSummaryMail1 = 2130968650;
			
			// aapt resource value: 0x7f040051
			public const int textViewSummaryMail2 = 2130968657;
			
			// aapt resource value: 0x7f040044
			public const int textViewSummaryName1 = 2130968644;
			
			// aapt resource value: 0x7f04004b
			public const int textViewSummaryName2 = 2130968651;
			
			// aapt resource value: 0x7f040049
			public const int textViewSummaryPhone1 = 2130968649;
			
			// aapt resource value: 0x7f040050
			public const int textViewSummaryPhone2 = 2130968656;
			
			// aapt resource value: 0x7f040046
			public const int textViewSummaryRegNo1 = 2130968646;
			
			// aapt resource value: 0x7f04004d
			public const int textViewSummaryRegNo2 = 2130968653;
			
			// aapt resource value: 0x7f040045
			public const int textViewSummarySSN1 = 2130968645;
			
			// aapt resource value: 0x7f04004c
			public const int textViewSummarySSN2 = 2130968652;
			
			// aapt resource value: 0x7f040000
			public const int textViewUppgifterFörare = 2130968576;
			
			// aapt resource value: 0x7f040016
			public const int textViewWrongUserAndPassword = 2130968598;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataDriver = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DescriptionAccident = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Forgotpassword = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Registeraccount = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RegistrationNo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SelectInsuranceCompany = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Sent = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Summary = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TakePhoto = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
